### PR TITLE
Fix timer requests in update and lifecycle.

### LINKED ISSUE #834: Briefly show the scrollbars any time the Scroll widget's size changes
There's a `reset_scrollbar_fade(&mut self, ctx: &mut EventCtx, env: &Env)` function already that does this. The problem is that it requires the `EventCtx` because it uses a timer to achieve its goal. The `Scroll` only really knows its size has changed when `layout` gets called.

Is this an example that we need some new druid event for when our own size changes? Is there any way to plumb the timer request at all right now? It's not even possible to send commands from `layout` or `paint`.

Previously `Scroll` was listening to `Event::Size` but that was a mistake, because that event only gets sent to the root widget and means that the window size has changed. Window size changing doesn't necessarily mean the widget's size has changed even if we propagate that to every widget.

### PR DESCRIPTION
**Pull request by xStrom**
This PR fixes the handling of timer requests. Previously they were only collected in the window's `event` but I moved the collection to the general post processing step. I also removed the legacy `request_timer` `bool` which no longer served a purpose and was never being reset.

This also finally allowed to address #834. Scrollbars now briefly animate when the container is resized. This can be seen with e.g. the `scroll_colors` example when you resize the window.

Fixes #834.

### CODE REVIEW

File: druid/src/window.rs [hunk 1]
```diff
@@ -288,6 +293,8 @@ impl<T: Data> Window<T> {
         if ctx.base_state.request_anim {
             self.last_anim = Some(now);
         }
+
+        self.post_event_processing(&mut base_state, queue, data, env, process_commands);
```
Comment (cmyr) [inline druid/src/window.rs:297]: Is there a specific reason we think this is necessary? do_anim_frame is part of paint, and paint calls this already.

File: druid/src/widget/scroll.rs [hunk 2]
```diff
@@ -176,12 +176,15 @@ impl<T, W: Widget<T>> Scroll<T, W> {
     }
 
     /// Makes the scrollbars visible, and resets the fade timer.
-    pub fn reset_scrollbar_fade(&mut self, ctx: &mut EventCtx, env: &Env) {
+    pub fn reset_scrollbar_fade<F>(&mut self, request_timer: F, env: &Env)
```
[the remark this answers is not in the document]
Comment (xStrom) [reply druid/src/widget/scroll.rs:179]: Yeap, I was thinking of the same thing based on the amount of code duplication we have in `context.rs`. Then having to do this `request_timer` closure here really boosted that thinking. I have it in my notes to attempt to better the situation with traits. (*Would be a separate PR.*)

File: druid/src/window.rs (hunk 1 above)
Comment (xStrom) [reply druid/src/window.rs:297]: - It's necessary because a widget might call `submit_command` or `request_timer` in response to `AnimFrame`.
- `do_anim_frame` is currently part of `lifecycle` not `paint` and so even if `paint` called `post_event_processing` that wouldn't be guaranteed for other `AnimFrame` calls to `lifecycle`.
- `paint` doesn't call `post_event_processing`.
- `AnimFrame` does not guarantee `paint` in the future as discussed [on zulip](https://xi.zulipchat.com/#narrow/stream/147926-druid/topic/purpose.20of.20request_anim).

File: druid/src/util.rs [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+    /// and it should keep that allocation.
+    fn extend_drain(&mut self, source: &mut Self);
+}
+
+impl<K, V> ExtendDrain for HashMap<K, V>
+where
+    K: Eq + Hash + Copy,
+    V: Copy,
+{
+    fn extend_drain(&mut self, source: &mut Self) {
```
[the remark this answers is not in the document]
Comment (xStrom) [reply druid/src/util.rs:41]: There was a funny surprise alright. The empty target case is 0ns with this optimized function, which is a win. However unexpectedly even the slow path is faster! The slow path is faster only with `drain` though. If I bench extending with just `iter` vs `iter`, then the slow paths are equal. Some sort of non-generic code win I guess.

File: druid/src/widget/scroll.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (cmyr) [reply druid/src/widget/scroll.rs:179]: I am accidentally working on this right now.

File: druid/src/window.rs (hunk 1 above)
Comment (cmyr) [reply druid/src/window.rs:297]: in order:

- to my mind, `AnimFrame` should only be used to update state in preparation for an imminent paint call. This is a weird case;  `AnimFrame` is one of the bits of event flow that is really a poor fit to the current architecture, and when (like.... a year ago? 😬) I was playing around with a higher-level animation API, one of the changes was to just make a `prepare_for_animation` method on `Widget` that replaced `AnimFrame`. `submit_command` and `request_timer` should be discouraged here, and it's annoying that this isn't enforced by the type system.

- `do_anim_frame` sort of is part of paint; `LifeCycle::AnimFrame` should only be sent from `Window::do_paint`, if it happens anywhere else that's a mistake.

- this checks out, I must've misread again. That said, it looks like we  call `post_event_processing` in Window::lifecycle`, which is what calls `do_anim_frame`?

- I think this is false? it's not really that anim guarantees `paint`, it's that `AnimFrame` is only called from the painting code path.

File: druid/src/util.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (cmyr) [reply druid/src/util.rs:41]: neat, thanks for measuring!

File: druid/src/window.rs (hunk 1 above)
Comment (xStrom) [reply druid/src/window.rs:297]: * Yes we do call `post_event_processing` in `Window::lifecycle` right now, which means it also applies to `do_anim_frame`. However due to borrow checking limitations, in order to keep that functionality, I had to add it to `do_anim_frame` because the `Window::lifecycle` call moved into an `if` block.

* Yeah right now `AnimFrame` is sent just before `paint`. However based on that zulip discussion this may change. @raphlinus said *It's up to the handler of that lifecycle event to request painting* - from which I derive that if the handler doesn't request painting, the painting might not happen at all. (This is for future behavior, today that's not true.)

More generally, moving `AnimFrame` out of `lifecycle` makes sense if it's supposed to have different limitations. However as long as it's part of `lifecycle` I think it should behave like a `lifecycle` event. That includes a working `request_timer` and `submit_command`.

Comment (cmyr) [reply druid/src/window.rs:297]: On the second point: I think there's a confusion about raph's comments. `AnimFrame` _does_ mean you're going to paint; there's no short-circuiting. If you see it, it means a call to paint is next. To continue the animation, you *do* need to request another frame.

I'll take a look at the code you're talking about, I might've missed that.

File: druid/src/window.rs [hunk 4]
```diff
@@ -260,13 +260,18 @@ impl<T: Data> Window<T> {
             };
 
             self.root.lifecycle(&mut ctx, event, data, env);
+            self.post_event_processing(&mut base_state, queue, data, env, process_commands);
```
Comment (cmyr) [inline druid/src/window.rs:263]: we can move this out of the `if` branch if we move the `base_state` decl to above the block, this should solve our other little confusion?

Comment (xStrom) [reply druid/src/window.rs]: Yes! That will work.
